"use client";
import React, { useCallback, useEffect, useState } from "react";
import { Bell, Pencil, Plus, Trash2 } from "lucide-react";
import { apiFetch } from "@/lib/api";
import { alert, toast } from "@/lib/swal";
import { tx } from "@/app/lib/theme";

interface Announcement { id: string; title: string; body: string; target_group: string | null; created_at: string; }
interface Props { courseId: string; canManage?: boolean; selectedClass?: string; courseLevels?: string[]; }
export function CourseAnnouncements({ courseId, canManage = false, selectedClass = "all", courseLevels = [] }: Props) {
  const [items, setItems] = useState<Announcement[]>([]), [loading, setLoading] = useState(true), [editing, setEditing] = useState<Announcement | null>(null), [title, setTitle] = useState(""), [body, setBody] = useState(""), [target, setTarget] = useState("all"), [saving, setSaving] = useState(false);
  const load = useCallback(async () => { const suffix = canManage ? `&classContext=${encodeURIComponent(selectedClass)}` : ""; const { data } = await apiFetch<{ announcements: Announcement[] }>(`/api/announcements?courseId=${encodeURIComponent(courseId)}${suffix}`); setItems(data?.announcements || []); setLoading(false); }, [courseId, canManage, selectedClass]);
  useEffect(() => {
    let active = true;
    const suffix = canManage ? `&classContext=${encodeURIComponent(selectedClass)}` : "";
    void apiFetch<{ announcements: Announcement[] }>(`/api/announcements?courseId=${encodeURIComponent(courseId)}${suffix}`).then(({ data }) => {
      if (active) { setItems(data?.announcements || []); setLoading(false); }
    });
    return () => { active = false; };
  }, [courseId, canManage, selectedClass]);
  const reset = useCallback(() => { setEditing(null); setTitle(""); setBody(""); setTarget(selectedClass === "all" ? "all" : selectedClass); }, [selectedClass]);
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (!title.trim()) return; setSaving(true); const payload = editing ? { id: editing.id, title, body, classContext: selectedClass } : { courseId, title, body, classContext: selectedClass, targetGroup: selectedClass === "all" ? (target === "all" ? null : target) : selectedClass }; const { error } = await apiFetch("/api/announcements", { method: editing ? "PUT" : "POST", body: JSON.stringify(payload) }); setSaving(false); if (error) return toast.error(error); const wasEditing = !!editing; reset(); await load(); toast.success(wasEditing ? "บันทึกการแก้ไขประกาศแล้ว" : "เผยแพร่ประกาศแล้ว"); };
  const remove = async (id: string) => { if (!await alert.confirm("ลบประกาศ?", "นักเรียนจะไม่สามารถดูประกาศนี้ได้อีก", "ลบ")) return; const { error } = await apiFetch(`/api/announcements?id=${encodeURIComponent(id)}&classContext=${encodeURIComponent(selectedClass)}`, { method: "DELETE" }); if (error) return toast.error(error); await load(); toast.success("ลบประกาศแล้ว"); };
  return <section className="rounded-3xl border p-4 md:p-5 space-y-4" style={{ backgroundColor: tx.surface, borderColor: tx.borderS }}>
    <div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><span className="h-8 w-8 rounded-xl bg-amber-500/10 text-amber-500 flex items-center justify-center"><Bell className="h-4 w-4" /></span><div><h2 className="font-extrabold text-sm">ประกาศ</h2><p className="text-xs" style={{ color: tx.muted }}>ข่าวสารและการแจ้งเตือนจากผู้สอน</p></div></div>{canManage && !editing && title === "" && <button type="button" onClick={() => { setTitle(" "); setTarget(selectedClass === "all" ? "all" : selectedClass); }} className="btn-primary px-3 py-2 text-xs flex items-center gap-1.5"><Plus className="h-3.5 w-3.5" />เพิ่มประกาศ</button>}</div>
    {canManage && (editing || title !== "") && <form onSubmit={save} className="rounded-2xl border p-3 space-y-3" style={{ borderColor: tx.borderS, backgroundColor: tx.elevated }}><input autoFocus value={title} onChange={(e) => setTitle(e.target.value)} maxLength={160} placeholder="หัวข้อประกาศ" className="w-full rounded-xl border px-3 py-2 text-sm bg-transparent" style={{ borderColor: tx.borderS }} />{!editing && selectedClass === "all" && <select value={target} onChange={(e) => setTarget(e.target.value)} className="w-full rounded-xl border px-3 py-2 text-sm bg-transparent" style={{ borderColor: tx.borderS }}><option value="all">ทุกชั้น</option>{courseLevels.map((level) => <option key={level} value={level}>{level}</option>)}</select>}<textarea value={body} onChange={(e) => setBody(e.target.value)} maxLength={5000} rows={4} placeholder="เขียนรายละเอียดสำหรับนักเรียน" className="w-full rounded-xl border px-3 py-2 text-sm bg-transparent resize-y" style={{ borderColor: tx.borderS }} /><div className="flex justify-end gap-2"><button type="button" onClick={reset} className="btn-cancel px-3 py-2 text-xs">ยกเลิก</button><button disabled={saving || !title.trim()} className="btn-primary px-3 py-2 text-xs">{saving ? "กำลังบันทึก..." : editing ? "บันทึกการแก้ไข" : "เผยแพร่ประกาศ"}</button></div></form>}
    {loading ? <p className="text-xs" style={{ color: tx.muted }}>กำลังโหลดประกาศ...</p> : items.length === 0 ? <p className="text-sm py-2" style={{ color: tx.muted }}>ยังไม่มีประกาศในขณะนี้</p> : <div className="space-y-3">{items.map((a) => <article key={a.id} className="rounded-2xl border p-3.5" style={{ borderColor: tx.borderS }}><div className="flex justify-between gap-3"><div><h3 className="font-bold text-sm">{a.title}</h3><p className="text-[11px] mt-1" style={{ color: tx.muted }}>{new Date(a.created_at).toLocaleString("th-TH")}{canManage && selectedClass === "all" && <span className="ml-2">{a.target_group ?? "ทุกชั้น"}</span>}</p></div>{canManage && <div className="flex gap-1"><button type="button" aria-label="แก้ไขประกาศ" onClick={() => { setEditing(a); setTitle(a.title); setBody(a.body); }} className="btn-icon p-1.5 rounded-lg"><Pencil className="h-3.5 w-3.5" /></button><button type="button" aria-label="ลบประกาศ" onClick={() => void remove(a.id)} className="btn-icon p-1.5 rounded-lg text-red-500"><Trash2 className="h-3.5 w-3.5" /></button></div>}</div>{a.body && <p className="mt-3 text-sm whitespace-pre-wrap" style={{ color: tx.secondary }}>{a.body}</p>}</article>)}</div>}
  </section>;
}
